language: php
php:
  - 5.4
  - 5.5

before_script:
   - composer --quiet install
   - composer --quiet --working-dir=tests install

script: php ./tests/testall.php

notifications:
  email: false
  irc: "open.ircnet.org#ariadne"

